import type { Metadata } from "next";
import "./globals.css";
import { ReactQueryClientProvider } from "@/providers/ReactQueryClientProvider";
import { MuiThemeProvider } from "@/providers/MuiThemeProvider";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "10FoodHotel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MuiThemeProvider>
          <ReactQueryClientProvider>
            <Toaster position="top-center"/>
            {children}
          </ReactQueryClientProvider>
        </MuiThemeProvider>
      </body>
    </html>
  );
}
